### ISSUE TITLE
Selection de variables

### ISSUE THREAD

**Issue by killiankopp** [pebble-solutions/app-mate.save#9]
<img width="425" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0FOQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--484db56073c68d3f5efa9289de9cf7fb0754bf54/Capture%20d%E2%80%99e%CC%81cran%202024-01-30%20a%CC%80%2009.24.49.png" alt="Capture d’écran 2024-01-30 à 09.24.49.png" />

La sélection de variable n'affiche pas la description qui est utile pour savoir s'il s'agit bien de la bonne variable et à quoi elle sert.

Créer une nouvelle sélection avec l'affichage du label et de la description en tenant compte des dates de disponibilités de la variable.

**Comment by deathtroll22** [comment]
Aucune de tes images importée ne s'affiche ! Sur aucun des gitissues
